## config.toml
## Example replication-manager configuration file

## change the service file  in /etc/systemd/system/replication-manager.service to looks like :
## replication-manager-osc  --config=./etc/config.toml.sample  --cluster=Cluster01,Cluster_Test_2_Nodes monitor

[Cluster_Haproxy_A]
title = "ClusterTestMasterSlave"

db-servers-hosts = "127.0.0.1:3310,127.0.0.1:3311"
db-servers-prefered-master = "127.0.0.1:3310"
db-servers-credential = "root:test"
db-servers-connect-timeout = 1

replication-credential = "root:test"
replication-source-name = "cluster_a"
force-slave-readonly = false
haproxy = true
haproxy-write-port = 3303
haproxy-read-port = 3302
haproxy-api-port = 1999
haproxy-stat-port = 1998


[Cluster_Haproxy_B]
title = "ClusterTestMasterSlave"

db-servers-hosts = "127.0.0.1:3313,127.0.0.1:3314"
db-servers-prefered-master = "127.0.0.1:3313"
db-servers-credential = "root:test"
db-servers-connect-timeout = 1

replication-credential = "root:test"
replication-source-name = "cluster_b"

haproxy = true
haproxy-write-port = 3304
haproxy-read-port = 3305
haproxy-api-port = 1979
haproxy-stat-port = 1978
