[Default]
# log-heartbeat = true
include ="etc/opensvc/cluster-api/cluster-demo/stephane.d"
log-file="/var/log/replication-manager.log"
http-bind-address = "0.0.0.0"
api-credentials = "admin:hash_ac60e1f5625dfb87f67af46c04424cabc28f5ad77799"

#VPN Address
monitoring-address = "10.8.0.50"
#monitoring-ssl-cert="/Users/apple/.ssh/id_rsa"
#monitoring-ssl-key="/Users/apple/.ssh/id_rsa.pub"

opensvc-use-collector-api = false
opensvc-p12-certificate = "etc/opensvc/cluster-api/cluster-demo/signal18.p12"
opensvc-host = "10.8.0.15:1215"
opensvc-p12-secret = "hash_2e7c615c761028b57da0cf97effe9fb5befe81618b634f5466259c334ab810d2"

prov-orchestrator = "opensvc"
prov-orchestrator-cluster = "cloud18"
prov-net-cni = true
prov-net-cni-cluster = "repman"
prov-docker-daemon-private=false
prov-db-agents = "s18-fr-1,s18-fr-2"
prov-db-service-type = "docker"
prov-db-disk-type = "volume"
prov-db-volume-data = "db"
prov-proxy-agents = "s18-fr-1,s18-fr-2"
prov-proxy-service-type = "docker"
prov-proxy-disk-type = "volume"
prov-proxy-volume-data = "tank"
test=true
cloud18 = false
cloud18-gitlab-user="stephane@signal18.io"
cloud18-gitlab-password="hash_0472ff4acf82eb1afc0edd44c9087c9a95f4874adc38e3b2aa68496a"
cloud18-domain = "signal18"
cloud18-sub-domain = "ovh-dev"
cloud18-sub-domain-zone = "fr-1"


#proxyjanitor-servers = "51.68.2.60"
#proxyjanitor-password = "hash_c3fbd75e68b9f08db04620b592d48b9ac154bd97901e9064ea8dd2938f4a6a8e"

monitoring-save-config=true
#git-url="https://gitlab.signal18.io/signal18/ovh-fr-1"
#git-username ="svaroqui"
#git-acces-token="hash_39d6c7a2aded0a01a954c5de3de1405866b9c9273e4515afa4a26fa6a302e9f37446a1093b1cbf04e6c4"

#mail-from = "support@signal18.io"
#mail-to = "stephane@signal18.io"
#mail-smtp-addr = "in-v3.mailjet.com:587"
mail-smtp-user = "53b0c2c80298023abf083a106261c789"
mail-smtp-password = "hash_497b7124700d1a7ffaacbc88d672f92714a4bfda2f0ae3747a8647c8bf75db2809513f4f54463d081ab2813ac8c45e8d"
alert-pushover-app-token="hash_046d7d15e81ebbfe4e6e55ac1a3bb3312612c2a52a32cf3fde26b49260b32d043f113904e8e124f9e01ea12e8fd0"
alert-pushover-user-token="hash_d86ad53bf75115156e75cf9fb86f25659d62a2407972635e4a04ea630bdaf9366f7c9905433f343e2f8809ea5cb2"


#arbitration-external= true
#arbitration-external-hosts="10.8.0.50:8080"
#arbitration-peer-hosts="10.8.0.72:10001"
#arbitration-external-secret="tnstest"

backup-restic-aws-access-secret = "hash_7522e94c4ceb43505c950e856742345a473a3d2e1a9d6450679bede9"
backup-restic-password = "hash_7522e94c4ceb43505c950e856742345a473a3d2e1a9d6450679bede9"
#backup-streaming = true
backup-streaming-aws-access-key-id = "admin"
backup-streaming-aws-access-secret = "hash_7522e94c4ceb43505c950e856742345a473a3d2e1a9d6450679bede9"
backup-streaming-endpoint= "https://s3.signal18.io/"
backup-streaming-region= "fr-1"
backup-streaming-bucket= "repman"
backup-mysqldump-path = "/usr/local/bin/mysqldump"
graphite-embedded     = true
graphite-metrics = true
