[Default]

opensvc-use-collector-api = false
opensvc-p12-certificate = "etc/opensvc/cluster-api/cluster-demo/signal18.p12"
opensvc-host = "10.8.0.15:1215"
opensvc-p12-secret = "36vf2cczf8rms8hh"

include ="etc/opensvc/cluster-api/cluster-demo/stephane.d"
# log-heartbeat = true

log-file="/var/log/replication-manager.log"
http-bind-address = "0.0.0.0"

#VPN Address
monitoring-address = "10.8.0.50"


prov-orchestrator = "opensvc"
prov-orchestrator-cluster = "cloud18"

prov-net-cni = true
prov-net-cni-cluster = "repman"

prov-docker-daemon-private=false

prov-db-agents = "s18-fr-1,s18-fr-2"

prov-db-service-type = "docker"
prov-db-disk-type = "volume"
prov-db-volume-data = "db"

prov-proxy-agents = "s18-fr-1,s18-fr-2"
prov-proxy-service-type = "docker"
prov-proxy-disk-type = "volume"
prov-proxy-volume-data = "tank"
test=true


alert-pushover-app-token="ad5t1i6m4491ioauubaitqtg1kewtu"
alert-pushover-user-token="uixs8gufi8859u8k8zqeojx7i948fi"

#monitoring-ssl-cert="/Users/apple/.ssh/id_rsa"
#monitoring-ssl-key="/Users/apple/.ssh/id_rsa.pub"

#arbitration-external= true
#arbitration-external-hosts="10.8.0.50:8080"
#arbitration-peer-hosts="10.8.0.72:10001"
#arbitration-external-secret="tnstest"
