[tnstest]
title = "tnstest"
db-servers-hosts = "db1,db2"
db-servers-prefered-master = "db1"
# prov-orchestrator = "onpremise"
# db-servers-prefered-master = "db1.benchsvc.cloud18"
# db-servers-hosts = "db1.bench.svc.cloud18,db2.bench.svc.cloud18"
db-servers-credential = "root:mariadb"

#replication-source-name = "bench"
#prov-db-domain = "1"

#replication-multi-master-wsrep = false
db-servers-connect-timeout = 1
replication-credential = "root:mariadb"
#force-slave-readonly = true
#prov-db-docker-img = "quay.io/mariadb-foundation/mariadb-devel:10.8-mdev-11675-rpl-lag-free-alter"
prov-db-docker-img = "mariadb:10.3.32"

prov-db-tags = "smallredolog,docker,linux,innodb,noquerycache,threadpool,slow,ssd,localinfile,nodoublewrite,compressbinlog,noadaptiveflush,relayspacelimit,optimistic"
prov-db-disk-size = "2"
prov-db-memory = "256"
prov-db-disk-iops = "10000"
prov-db-cpu-cores = "8"


monitoring-scheduler = false
sysbench-binary-path ="/usr/local/bin/sysbench"
sysbench-v1 = true

# backup-restic = true

prov-proxy-disk-size = "1"


proxysql=true
proxysql-servers = "proxysql1"
proxysql-user ="external"
proxysql-bootstrap= true
proxysql-copy-grants = true




#maxscale=true
#maxscale-servers = "maxscale1"

#haproxy=true
#haproxy-servers = "haproxy1"
# haproxy-servers = "haproxy1.bench.svc.cloud18"

#shardproxy=true
#hardproxy-servers = "shardproxy1"
#prov-proxy-docker-shardproxy-img="signal18/mariadb-spider:latest"
